/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bg_x2d_Local */

#ifndef _Included_bg_x2d_Local
#define _Included_bg_x2d_Local
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bg_x2d_Local
 * Method:    getGraphicsDevice
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_bg_x2d_Local_getGraphicsDevice
  (JNIEnv *, jclass);

/*
 * Class:     bg_x2d_Local
 * Method:    getSystemAvailableRAM
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_bg_x2d_Local_getSystemAvailableRAM
  (JNIEnv *, jclass);

/*
 * Class:     bg_x2d_Local
 * Method:    getSystemTotalRAM
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_bg_x2d_Local_getSystemTotalRAM
  (JNIEnv *, jclass);

/*
 * Class:     bg_x2d_Local
 * Method:    getProcessId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_bg_x2d_Local_getProcessId
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
